### ISSUE TITLE
Imports of modules used by `workflow.py`.

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#65]
When a workflow is ran using `workflow run` or `workflow run-local` the `workflow.py` file is imported dynamically. It seems that, even when in the same directory as `workflow.py`,  modules used by workflow.py which are not installed under `site-packages` cannot be found to be imported. 

 My assumption is that when `workflow.py` is imprted the working directory is not the directory containing `workflow.py` at the time of the import.

**Comment by BlakeASmith** [comment]
For an example, the [workflow-pathoscope](https://github.com/BlakeASmith/workflow-pathoscope) workflow has a `pathoscope.py` module which is imported within `workflow.py`.

```
pathoscope_1  | Traceback (most recent call last):
pathoscope_1  |   File "/root/.local/bin/workflow", line 8, in 
pathoscope_1  |     sys.exit(cli_main())
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/cli.py", line 109, in cli_main
pathoscope_1  |     cli()
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
pathoscope_1  |     return self.main(*args, **kwargs)
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
pathoscope_1  |     rv = self.invoke(ctx)
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
pathoscope_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
pathoscope_1  |     return ctx.invoke(self.callback, **ctx.params)
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
pathoscope_1  |     return callback(*args, **kwargs)
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/cli.py", line 58, in run
pathoscope_1  |     asyncio.run(_run(f, job_id, **kwargs))
pathoscope_1  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
pathoscope_1  |     return loop.run_until_complete(main)
pathoscope_1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
pathoscope_1  |     return future.result()
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/cli.py", line 45, in _run
pathoscope_1  |     workflow, _ = discovery.run_discovery(Path(file), Path(file).parent / "fixtures.py")
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/discovery.py", line 111, in run_discovery
pathoscope_1  |     fixtures.extend(load_fixtures_from__fixtures__(path))
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/discovery.py", line 54, in load_fixtures_from__fixtures__
pathoscope_1  |     module = _import_module_from_file(path.name.rstrip(path.suffix), path)
pathoscope_1  |   File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/discovery.py", line 28, in _import_module_from_file
pathoscope_1  |     module = spec.loader.load_module(module_from_spec(spec).__name__)
pathoscope_1  |   File "", line 469, in _check_name_wrapper
pathoscope_1  |   File "", line 969, in load_module
pathoscope_1  |   File "", line 794, in load_module
pathoscope_1  |   File "", line 274, in _load_module_shim
pathoscope_1  |   File "", line 711, in _load
pathoscope_1  |   File "", line 680, in _load_unlocked
pathoscope_1  |   File "", line 790, in exec_module
pathoscope_1  |   File "", line 228, in _call_with_frames_removed
pathoscope_1  |   File "workflow.py", line 4, in 
pathoscope_1  |     import pathoscope
pathoscope_1  | ModuleNotFoundError: No module named 'pathoscope'

```

**Comment by igboyes** [comment]
Can you take a look at how this works with test file discovery in `pytest`? It is a similar situation.

**Comment by BlakeASmith** [comment]
> Can you take a look at how this works with test file discovery in `pytest`? It is a similar situation.

Sounds like a good idea. I can't find much online for the issue. I'll have a leaf through the pytest source.
